name: node-reporter CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install, build and test
        working-directory: ./app
        run: |
          npm install
          npm run build
      - name: Push changes to repo
          run: |
            REMOTE=https://${{ secrets.GH }}@github.com/${{ github.repository }}
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git config user.name "${{ github.actor }}"
            git pull ${REMOTE}
            git checkout master
            git add .
            git status
            git commit -am "build pages"
            git push ${REMOTE} master

